# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Desarrollando al Desarrollador
email: jim.acero.valcarcel@gmail.com
description: >- #
  Blog de un desarrollador web fullstack, con varios años de experiencia dispuesto a aprender cada día.
twitter_username: username
github_username: joav
minimal_mistakes_skin: default
search: true
url: https://joav.github.io
baseurl: /desarrollando-al-desarrollador
locale: es
keywords:
  - desarrollador
  - fullstack
  - dev
  - blog
  - joav
  - github
  - development
  - software
  - arquitectura de software
  - frontend
  - backend
repository: joav/desarrollando-al-desarrollador
date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

enable_copy_code_button: true
comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
    label: "blog-comment"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-09X2VW49YQ"
    anonymize_ip: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jimmy Acero"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Desarrollador web fullstack, con título de Ingeniero en Multimedia. AWS Certified Solutions Architect - Associate. Apasionado por la web, las APIs, cloud, arquitectura de software…"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ingenierojimmyacero.netlify.app?utm_source=blog-desarrollando-al-desarrollador&utm_medium=blog&utm_content=author_card"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joav"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jimmy-acero"
    - label: "Threads"
      icon: "fab fa-fw fa-threads"
      url: "https://www.threads.net/@acerojimmy"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ingenierojimmyacero.netlify.app?utm_source=blog-desarrollando-al-desarrollador&utm_medium=blog&utm_content=footer_link"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joav"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jimmy-acero"
    - label: "Threads"
      icon: "fab fa-fw fa-threads"
      url: "https://www.threads.net/@acerojimmy"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categorias/
tag_archive:
  type: liquid
  path: /tags/
